// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc5490.RealRobot.commands;

import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc5490.RealRobot.Robot;

import  org.usfirst.frc5490.RealRobot.subsystems.driveTrain;

/**
 *
 */
public class  Move extends Command {


    public Move() {
        // Use requires() here to declare subsystem dependencies
        // eg. requires(chassis);

        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.driveTrain);
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    // Called just before this Command runs the first time
    protected void initialize() {
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {

        drive left = new drive();
            double driveLeft = left.leftMotor();
        drive right = new drive();
            double driveRight = right.rightMotor();

        double driveTotal = driveLeft + driveRight;

        if (driveTotal > 0) {
        RobotMap.driveTrainLeftFront.set(driveLeft);
        RobotMap.driveTrainLeftRear.set(driveLeft);
        RobotMap.driveTrainRightFront.set(-driveRight);
        RobotMap.driveTrainRightFront.set(-driveRight);
    }   else {
        RobotMap.driveTrainLeftFront.set(0);
        RobotMap.driveTrainLeftRear.set(0);
        RobotMap.driveTrainRightFront.set(0);
        RobotMap.driveTrainRightFront.set(0);
    }
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return false;
    }

    // Called once after isFinished returns true
    protected void end() {
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    }
}
